### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by zainkhan-afk** [betajippity/Onepu#1]
Hi
I tried compiling your code but kept getting the following linker errors:

```
LNK2019: unresolved external symbol "public: class Eigen::Matrix<float,3,1,0,3,1> __cdecl Eigen::MatrixBase<class Eigen::Matrix<float,3,1,0,3,1> >::cross<class Eigen::Matrix<float,3,1,0,3,1> >(class Eigen::MatrixBase<class Eigen::Matrix<float,3,1,0,3,1> > const &)const " (??$cross@V?$Matrix@M$02$00$0A@$02$00@Eigen@@@?$MatrixBase@V?$Matrix@M$02$00$0A@$02$00@Eigen@@@Eigen@@QEBA?AV?$Matrix@M$02$00$0A@$02$00@1@AEBV01@@Z) referenced in function "class spatialmathCore::svec6 __cdecl spatialmathCore::applySpatialTransformToAdjoint(class spatialmathCore::svec6 const &,class spatialmathCore::stransform6 const &)" (?applySpatialTransformToAdjoint@spatialmathCore@@YA?AVsvec6@1@AEBV21@AEBVstransform6@1@@Z)

LNK2001: unresolved external symbol "public: class Eigen::Matrix<float,3,1,0,3,1> __cdecl Eigen::MatrixBase<class Eigen::Matrix<float,3,1,0,3,1> >::cross<class Eigen::Matrix<float,3,1,0,3,1> >(class Eigen::MatrixBase<class Eigen::Matrix<float,3,1,0,3,1> > const &)const " (??$cross@V?$Matrix@M$02$00$0A@$02$00@Eigen@@@?$MatrixBase@V?$Matrix@M$02$00$0A@$02$00@Eigen@@@Eigen@@QEBA?AV?$Matrix@M$02$00$0A@$02$00@1@AEBV01@@Z)
```

I saw a fix online that said that I should replace #include <Eigen/Core> with #include <Eigen/Dense>, that fixed the linker error and the code is compiling too, however, there is an exception that occurs when the bodies are added to the rig. The exception originates from the Eigen files I think. 

I am using Visual Studio Microsoft Visual Studio Community 2022  for compiling the code. I cloned your NUPARU master branch. I have my own implementation of Articulated Body Algorithm and I wanted to see the behavior of your algorithm to verify if mine was working. 

Thank you.

**Comment by betajippity** [comment]
Hi,

This is a really old school project; unfortunately I no longer provide active support for this project.
